import { ObeliscoVersion } from '../interfaces/versions.interfaces';

export const OBELISCO_VERSIONS: ObeliscoVersion[] = [
  {
    version: '1.55.1',
    date: '24/10/23',
    pullRequest: 'fix: variante colapsable color blanco (#202)',
    changes: [
      'Colapsables: se agrega variante colapsable color blanco, correcciones de estilos',
      'Navegación y pestañas: ajuste en line-height',
      'Desplegables: ajuste en line-height y box-shadow',
      'Header: mejoras en accesibilidad de header, se agrega skip-link y role banner ',
    ],
    other: [
      {
        version: '1.55.1',
        date: '23/10/2023',
        changes: [
          'Refactor: docs: se reemplazan scripts en documentación por actualización de bootstrap v4.6 (#204)',
        ],
      },
    ],
  },
  {
    version: '1.55.0',
    date: '18/10/2023',
    pullRequest: 'feat: header (#203)',
    changes: ['Versión oficial de header'],
  },
  {
    version: '1.54.0',
    date: '18/10/2023',
    pullRequest: 'fix: update de header (#199)',
    changes: ['versión de prueba'],
  },
  {
    version: '1.53.0',
    date: '09/10/2023',
    pullRequest: 'fix: update bootstrap v4 #200',
    changes: ['Actualización de bootstrap a versión 4.6.2'],
  },
  {
    version: '1.52.4',
    date: '03/10/2023',
    pullRequest: 'Bug Fixes',
    changes: ['Corrección en extend sass (en listas de accesos)'],
  },
  {
    version: '1.52.3',
    date: '28/09/2023',
    pullRequest: 'fix: fix-1_52_2 (#197)',
    changes: [
      'Navegación horizontal: se modifica el max height de nav horizontal',
      'Panel grande horizontal: se modifica para que card-body tome el ancho completo aunque tengan poco texto',
      'Panel grande vertical: se agrega aspect ratio 16:9 a imagen en panel vertical',
      'Accesos:',
      'Lista de Accesos: se extiende la clase card deck a access deck para el mismo comportamiento en accesos',
      'Se comenta temporalmente sección Accesos horizontal y vertical',
      'Se actualiza nombre de Con bordes a Estados',
      'Bloque (iniciar trámite): se agrega en organismos como Bloque (previamente Botones-Organismos, previo Botón en caja).',
      'Desplegables: corrección en item-danger (cerrar sesión) en desplegables cuando está deshabilitado. Se agrega disabled a desplegable de selección. Se corrige radio en desplegable',
      'Pestañas: corrección sizes en tabs',
      'Barra de desplazamiento horizontal: se agregan estilos temporales a la barra de desplazamiento horizontal de la clase',
      'Enlaces: se corrige focus en logo del header (imágenes)',
      'Buscador-Formularios: se corrige estilos en focus del botón reset del buscador',
      'Tarjetas: se agrega Lista desplazable para noticias en tarjetas',
    ],
  },
  {
    version: '1.52.2',
    date: '14/09/2023',
    pullRequest: 'fix: enlace y lista de enlaces (#196)',
    changes: [
      'Enlace: se cambia el grosor del focus únicamente en los enlaces de textos. Se modifica color de focus, hover, visited. Se agrega muestra de enlace dentro de tag small. Se cambian los iconos: external, access, download. Se cambia espaciado entre texto y el icono, ahora es de 2px. Se cambia la medida de los iconos a 20px. Se cambia el grosor de la línea del text-decoration. Se agrega variante blanco en fondo oscuro',
      'Lista informativa',
      'Lista de enlaces: Con viñeta y con check. Se modifica estilos en panel chico que contiene lista de enlace',
    ],
  },
  {
    version: '1.52.1',
    date: '31/08/2023',
    pullRequest: 'fix: fix 1.51.0 (#195)',
    changes: [
      'Cambio de nombre en clases contenedoras de los componentes, organismos, formulario',
      'Inicio / Instalación: Corrección de url de "Ver la documentación de componentes". Se modifica texto de definición de Obelisco en Instalación',
      'Se agrega clase universal de scroll horizontal (responsive-scroll)',
      'Tabla:',
      'Se agrega tabla responsive, con clase responsive-scroll.',
      'Se corrige que la tabla (table-bordered) no pierda el borde cuando se encuentra dentro de contenedor con clase responsive-scroll.',
      'Corrección de accesibilidad y focus en tabla responsive',
      'Paginado:',
      'Se corrige z-index cuándo page-ítem está activo.',
      'Ajuste de espaciados de paginado en mobile para cuando tenga 3 o 4 cifras (se comenta con equipo de Diseño, el componente estuvo pensado para 2 cifras).',
      'Ajuste en padding de no-events de paginado',
      'Header:',
      'Se cambian ids por clases en el scss y ajuste de padding.',
      'ajuste en padding de navbar.',
      'Se elimina icon-search y icon-close de aria-controls de header.',
      'Se reemplaza justify-content: end; por justify-content: flex-end;.',
      'Ajuste en width de enlace nav-link de header',
      'Pestañas:',
      'Se reemplaza div por button en flechas de pestañas desplazables.',
      'Se elimina la clase px-0 de pestañas.',
      'Se agrega contenido de pestañas en el componente',
      'Se ajustan aspectos de accesibilidad (ids y aria-label)',
      'Colapsables: corrección en html de colapsable (se eliminan ids innecesarios) y se convierte texto de descripción de <Collapse> en variable.',
      'Lista de pasos: corrección de z-index y posicionamiento de after en lista de pasos',
      'Enlaces: se agrega display: inline-block; y width: fit-content; en enlace para que se visualice correctamente cuando se hace focus.',
      'Accesos y Cards: se agrega width: 100% para que no tome el width fit-content de enlaces',
      'Desplegables: corrección de alineación de texto de item-text en desplegable',
    ],
  },
  {
    version: '1.52.0',
    date: '24/08/2023',
    pullRequest: 'feat: desplegables de selección y navegación (#162)',
    changes: [
      'Desplegables: se agregan desplegables de selección y navegación',
    ],
  },
  {
    version: '1.51.0',
    date: '07/08/2023',
    pullRequest: 'feat: banner (#194)',
    changes: ['Banner: se agrega componente banner'],
  },
  {
    version: '1.50.1',
    date: '26/07/2023',
    pullRequest: 'fix: 1.51 (#192)',
    changes: ['Corrección de errores en versión 1.51'],
  },
  {
    version: '1.50.0',
    date: '17/07/2023',
    pullRequest: 'Listas - Lista de pasos (#191)',
    changes: ['Lista de pasos: se corrigen errores'],
  },
  {
    version: '1.49.3',
    date: '12/07/2023',
    pullRequest: 'fix: gallery de html a react (#188)',
    changes: [
      'Se pasa el componente de html a react, ajustes a la visualización de las grillas, se corrige el borde de modal, ajustes en el componente, ajustes en el nombre del componente, mejoras a la proporción de imágenes (aspect-ratio 3/2) y nombre del contenedor en storybook',
    ],
  },
  {
    version: '1.49.2',
    date: '11/07/2023',
    pullRequest: 'Dev 1.49.1',
    changes: [
      'Se agrega word-break en enlace',
      'Se ajusta color de tag a cuando tiene clase btn en alerta',
      'Se corrige modal',
      'Se corrige footer info (indicador de utilidad)',
      'Se ajusta display de enlace dentro de panel y cards (display inline-block)',
      'Se prueba solución en header buscador en mobile',
    ],
  },
  {
    version: '1.49.1',
    date: '30/06/2023',
    pullRequest: 'fix: 1.49.1',
    changes: [
      'Versión 1.49',
      'Fix img aspect-ratio',
      'Se agrega object position center',
      'Se corrigen las rutas de cards',
      'Alert, se saca el display flex y se ajusta color de enlace en botón btn',
      'img en panel',
      'cambio de imagen en panel',
    ],
  },
  {
    version: '1.49.0',
    date: '29/06/2023',
    pullRequest: 'feat: switch (#187)',
    changes: [
      'Se agrega el componente nuevo switch',
      'Ajuste en radio en disposición flex',
      'Se agrega wrap en contenedor de imágenes de footer para dispositivos menores a 300px',
      'Se saca palabra Menú en el botón header mobile',
      'Se agrega estilos para evitar que rompan los textos en colapsable cuando están en mobile',
    ],
  },
  {
    version: '1.48.4',
    date: '21/06/2023',
    pullRequest: 'fix: corrección en panel (#186)',
    changes: ['Corrección en panel que afectaba listas de tarjetas'],
  },
  {
    version: '1.48.3',
    date: '14/06/2023',
    pullRequest: 'fix_panel (#185)',
    changes: [
      'Se agregan nuevas variantes del componente panel',
      'Se agrega fondo al componente',
      'Se agrega panel horizontal',
    ],
  },
  {
    version: '1.48.2',
    date: '01/06/2023',
    pullRequest: 'fix_generales (#184)',
    changes: [
      'Se agrega favicon en storybook',
      'Corrección de tipografía en label de forms',
      'Corrección en paddingleft de buscador, y posición de icono reset',
      'Corrección de focus en enlaces de footer',
      'Corrección de icono en enlace download-link',
      'Corrección en footer de url de oficios judiciales',
      'Ajuste en icono reset del buscador y en url de oficios judiciales',
      'Ajuste de icono en colapsable',
      'Corrección en footer de transparencia activa',
      'Se cambia el favicon y ajustes al scss footer',
    ],
  },
  {
    version: '1.48.1',
    date: '04/05/2023',
    pullRequest: 'fix generales (#183)',
    changes: [
      'Corrección de gap en accesos con disposición vertical',
      'Se corrige alerta de error, y se modifica el orden de alertas en simple y con cierre',
      'Margin top y bottom en hr de colapsables',
      'Se agrega el object fit de panel horizontal',
      'Se agrega export de componente Spinner',
      'Ajuste en font size de subtítulo',
      'Se agrega el object fit cover a panel vertical',
      'Se formatea los archivos scss y ajuste en el txs de typography',
    ],
  },
  {
    version: '1.48.0',
    date: '03/05/2023',
    pullRequest: 'feat: dev #152',
    changes: [
      'Se agregan nuevas funcionalidades al componente spinner',
      'Se corrigen errores en el componente spinner y en el botón con spinner',
      'Se corrigen errores en la barra de progreso',
      'Se corrigen errores en los accesos',
      'Se agrega el componente collapse list',
      'Se corrigen errores en los botones',
      'Se modifica el archivo preview.ts para optimizar la organización de los componentes',
      'Se reemplaza el label por volanta en los colapsables, acorde a figma',
      'Se corrigen errores en el footer',
      'Se corrigen errores en el padding y backface-visibility de los colapsables',
      'Se modifica el orden de los organismos en el footer',
      'Se formatean los archivos scss de los componentes button card y list group',
    ],
  },
  {
    version: '1.47.1',
    date: '17/04/2023',
    pullRequest: 'fix: se actualiza el tsconfig y url de versión',
    changes: ['Se actualiza el tsconfig y url de versión'],
  },
  {
    version: '1.47.0',
    date: '14/04/2023',
    pullRequest: 'feat: Alerta - Tooltip - Paginador - Breadcrumb',
    changes: [
      'Se agregan los componentes alerta, tooltip, paginador y breadcrumb',
      'Se corrige el espaciado del icono en el botón, se agrega el icono de material icons al botón',
      'Se agrega el componente tooltip',
      'Se modifica la visualización del breadcrumb en storybook, se reemplaza el divider por el icono de material-icons-round, se corrigen los espaciados, se corrige el nombre en stories',
      'Se agrega la capacidad de cerrar la alerta',
      'Se corrige el paginador',
      'Se agrega la versión actual del paquete de manera dinámica',
      'Se agrega el componente de navegación por pestañas',
      'Se modifican los nombres de los componentes, se reemplazan los textos secundarios por epígrafes y se ajusta su tamaño de fuente',
    ],
  },
  {
    version: '1.46.2',
    date: '14/03/2023',
    pullRequest: 'fix: remover símbolo ~ deprecado',
    changes: ['Se reemplaza el símbolo ~ por node_modules'],
  },
  {
    version: '1.46.1',
    date: '16/02/2023',
    pullRequest: 'Fix obelisco 1 46 0',
    changes: [
      'Se agregan los estilos de validación para radio y checkbox',
      'Se corrige el espaciado mobile en card-deck',
      'Se corrigen los estilos de la tarjeta horizontal con icono sin borde',
      'Se corrigen los estilos en etiqueta para evitar desbordamiento',
      'Se cambia el icono logout del header',
      'Ajuste en posición de círculo azul de radio',
      'Se agrega clase group-access en listas por ancho tarjeta',
      'Modificación de font-family de titulo h5',
      'Modificación de font-weight de paginación y se reemplaza icono por el icono de material icons',
      'Se modifica addons en instalación, plantillas y releases',
      'Se modifica versión',
    ],
  },
  {
    version: '1.46.0',
    date: '07/02/2023',
    pullRequest: 'feat: Se agrega la sección versión',
    changes: ['Se agrega la sección versión'],
  },
  {
    version: '1.45.3',
    date: '30/01/2023',
    pullRequest: 'fix: fix de la versión 1.45.2',
    changes: [
      'Se corrigen los siguientes errores de la versión 1.45.2:',
      '* En el panel chico, horizontal y vertical, los botones en mobile no tenían ancho completo.',
      '* El espaciado entre botones en el panel chico, horizontal y vertical era incorrecto cuando el texto del botón era largo.',
      '* El card-body del panel chico, horizontal y vertical no estaba centrado.',
      'En el mensaje de estado, se agrega un margen cuando hay dos textos.',
      'Se finaliza la implementación del componente tarjeta lista card-column.',
      'En las tarjetas, en mobile, el card-title tiene un font-weight de 600.',
    ],
  },
  {
    version: '1.45.2',
    date: '17/01/2023',
    pullRequest: 'master: Arreglo de versionado',
    changes: [
      'Se corrige el versionado del paquete para que coincida con la versión actual.',
    ],
  },
  {
    version: '1.45.1',
    date: '17/01/2023',
    pullRequest: 'fix_audio',
    changes: [
      'Modificación del ancho en componente audio',
      'Navegación vertical: font-weight regular',
      'Font-weight pasar a 700 los que estén en 900',
      'Modificar el icono de alerta',
      'Texto pequeño: Texto con tamaño 11.7px (clase text-xs) y modificación en Galeria',
      'Titulo h5: el tamaño 17px en vez de 16px',
      'Arreglo svg en mensaje de estado',
    ],
  },
  {
    version: '1.45.0',
    date: '17/01/2023',
    pullRequest: 'feat_mensade_de_estado',
    changes: ['Creación del componente mensaje de estado'],
  },
  {
    version: '1.44.0',
    date: '17/01/2023',
    pullRequest: 'feat_button_outline',
    changes: ['Creación del componente botón con borde y en caja'],
  },
  {
    version: '1.43.2',
    date: '17/01/2023',
    pullRequest: 'fix-radio-accesos',
    changes: [
      'css en lista de accesos para el alto del componente',
      'css en focus checkbox-radio',
      'css para icono en desplegables',
    ],
  },
  {
    version: '1.43.1',
    date: '12/12/2022',
    pullRequest: 'fix_accordion',
    changes: ['css generales “prioridades”'],
  },
  {
    version: '1.43.0',
    date: '12/12/2022',
    pullRequest: 'feat',
    changes: ['Creación del componente tarjeta con icono vertical'],
  },
  {
    version: '1.42.0',
    date: '22/11/2022',
    pullRequest: 'feat_spinner',
    changes: ['Creación del componente spinner'],
  },
  {
    version: '1.41.1',
    date: '03/11/2022',
    pullRequest: 'fix_header',
    changes: [
      'Se modificaron estilos en el componente header en la versión mobile',
    ],
  },
  {
    version: '1.40.0',
    date: '01/11/2022',
    pullRequest: 'fix_list_group',
    changes: [
      'Se agregó la variante cerrar sesión (modo info)',
      'Se agregaron los accesos con icono como en los templates rrss (con mr-2)',
    ],
  },
  {
    version: '1.39.2',
    date: '01/11/2022',
    pullRequest: 'fix_progress_bar',
    changes: [
      'Se agregó la clase bg-color para la barra de estado. info/success',
    ],
  },
  {
    version: '1.39.1',
    date: '01/11/2022',
    pullRequest: 'fix_dropdown',
    changes: [
      'Se agregó en desplegable con enlaces. div con button -> ul con li más a.',
    ],
  },
  {
    version: '1.39.0',
    date: '22/08/2022',
    pullRequest: 'feat',
    changes: ['Se agregan nuevos colores #97'],
  },
];
